### ISSUE TITLE
Add support for regex MetricFilter

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-metrics-reporter#1]
The Dropwizard Metrics library supports filtering metrics for reporters using the [`MetricFilter`](http://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/MetricFilter.html) interface.

The plugins provided by this project should support a metrics filter based on regular expressions against the metric name.

**Comment by lennartkoopmann** [comment]
@joschi Could you review my changes for me? I'm really not a Maven expert and could need a second pair of eyes on the module structure.

**Comment by lennartkoopmann** [comment]
@joschi ping :)
