### ISSUE TITLE
Add support for AWS Cloudwatch

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-metrics-reporter#22]
https://github.com/blacklocus/metrics-cloudwatch

**Comment by alcampos** [comment]
@joschi Is there a method to get the NodeId from the MetricsAnythingReporterConfiguration?

**Comment by joschi** [comment]
@alcampos Please discuss this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
Closed via #25.
