### ISSUE TITLE
NoSuchMethodError: getHostText()

### ISSUE THREAD

**Issue by maciekm** [Graylog2/graylog-plugin-metrics-reporter#27]
Hi, all metric reporters using the `getHostText()` are failing.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
at org.graylog.plugins.metrics.statsd.providers.StatsdProvider.get(StatsdProvider.java:39)
```

graylog: 2.4.3
java: 1.8.0_161

**Comment by joschi** [comment]
@maciekm Thanks for reporting this!

Could you check out version 2.4.0-beta.3 of the reporter plugin you're using and provide some feedback if it works for you?
➡️ https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases/tag/2.4.0-beta.3

**Comment by maciekm** [comment]
@joschi thanks for the fix, tested the datadog one (`withStatsdHost`)  and it works as expected. Thanks
