### ISSUE TITLE
Graylog 3.0 support

### ISSUE THREAD

**Issue by dio99** [Graylog2/graylog-plugin-metrics-reporter#34]
will it be updated to work on 3.0 ?

**Comment by msharpe248** [comment]
Works for me on 3.0...

**Comment by ntimo** [comment]
I just installed `metrics-reporter-prometheus-2.4.0-beta.3.jar` and when I try to open https://graylog.domain.com/api/plugins/org.graylog.plugins.metrics.prometheus/metrics 

I get the following error:
`{"type":"ApiError","message":"HTTP 404 Not Found"}`

Does someone maybe know why?

**Comment by ChristianWeissCG** [comment]
We installed `metrics-reporter-prometheus-2.4.0-beta.4-SNAPSHOT.jar` and can confirm that it is working on  Graylog 3.0.2+1686930. We are using Prometheus 2.3.2 (Revision 71af5e29e81579).
The only difference to your version is a version bump, or you are using another version of Graylog.

The ticket reporter (@dio99) may want to add the name of the plugin where he experiences a problem, else we could close this ticket.

Independent from that i would love to see a version bump to a stable version name on metrics-reporter-prometheus. Or are there any reasons why this plugin should not be considered as stable (production-ready)?

**Comment by alexey-ban** [comment]
I have same problem like @ntimo in docker installation
graylog - 3.0.2 
metrics-reporter-prometheus-2.4.0-beta.3.jar 

----

Where could I download  metrics-reporter-prometheus-2.4.0-beta.4-SNAPSHOT.jar ?

**Comment by bernd** [comment]
We just released a [Graylog 3.x compatible version](https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases/tag/3.0.0).

@alexey-ban Please make sure to place the downloaded plugin into the Graylog plugin directory inside the Docker container. If you still have problems, please open a separate issue for this. Thank you!
