### ISSUE TITLE
Generic metric names for prometheus

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog-plugin-metrics-reporter#35]
The prometheus plugin uses metric names like this:

* org_graylog2_inputs_gelf_tcp_GELFTCPInput_5cc1bd20057c5200116dfdef_open_connections
* org_graylog2_lookup_adapters_5cc1bc798e510600109570d9_refresh_count
* org_graylog2_lookup_caches_5ca37df31210da0011143090_hits_total

It is really painful to write alarms for metrics like this. It would much better if the metrics would have names like this:

* org_graylog2_inputs_open_connections {module: gelf_tcp, input_id: 5cc1bd20057c5200116dfde}
* org_graylog2_lookup_adapters_refresh_count {adapter_id: 5cc1bc798e510600109570d9}
* org_graylog2_lookup_caches_hits_total {cache_id: 5ca37df31210da0011143090}

This would allow us to specify generic prometheus alarms and generic grafana dashboards.

**Comment by bernd** [comment]
Closing this issue because the built-in Prometheus exporter in the Graylog server is using a better naming schema and also allows custom metric names.
