### ISSUE TITLE
metrics-reporter-elasticsearch usage

### ISSUE THREAD

**Issue by tyagirajnish** [Graylog2/graylog-plugin-metrics-reporter#36]
I have added this plugin and restarted the graylog but I don't know how to use it and there is no description mentioned anywhere, as we have in Prometheus plugin,

**Comment by bernd** [comment]
You can find the README for the elasticsearch module here: https://github.com/graylog-labs/graylog-plugin-metrics-reporter/blob/master/metrics-reporter-elasticsearch/README.md
