### ISSUE TITLE
datadog plugin setup help??

### ISSUE THREAD

**Issue by devopskid** [Graylog2/graylog-plugin-metrics-reporter#38]
I cant' seem to get the datadog metrics plugin to show up as a configurable input in the Graylog UI. Let me know if i've missed/misconfigured something.

Before building the .jar, I configured the "metrics-reporter-datadog" plugin by setting the following values in MetricsDatadogReporterConfiguration.java:

metrics_datadog_enabled = true
metrics_datadog_api_key = "myDatadogAPIkey"
metrics_datadog_hostname = "hostnameOfMyGraylogServer"

*i left all other values to be default*

Once i built the .jar with "mvn package", i placed it in /usr/share/graylog-server/plugin on my Graylog server and performed a "service graylog-server restart" , but i still do not see the ability to configure the plugin under "System/Inputs"

Other Info:
- im running graylog-server 3.0.0
- my version of maven is 3.6.2
- i have Graylog in a cluster of 2 EC2 nodes
- both nodes are sized r4.large

What am i missing here?

**Comment by GauthierMenier** [comment]
Up ?

**Comment by GauthierMenier** [comment]
Unfortunately we have exactly the same problem. Does anyone have an answer ?

**Comment by jalogisch** [comment]
use the release from here: https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases

and configure the plugin in your Graylog server.conf with the following parameter:

https://github.com/graylog-labs/graylog-plugin-metrics-reporter/blob/master/metrics-reporter-datadog/README.md

No UI is given for this.

**Comment by devopskid** [comment]
> use the release from here: https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases
> 
> and configure the plugin in your Graylog server.conf with the following parameter:
> 
> https://github.com/graylog-labs/graylog-plugin-metrics-reporter/blob/master/metrics-reporter-datadog/README.md
> 
> No UI is given for this.

Thanks for the info. I've downloaded the metrics-reporter-datadog-3.0.0.jar from the link you've provided.. Is there any modification required to the .jar file itself or do i just place it in the plugins directory and set my desired configuration in server.conf on the graylog server?
