### ISSUE TITLE
Graylog Internal Metrics should be ingestable into Graylog

### ISSUE THREAD

**Issue by iainmcinnes** [Graylog2/graylog-plugin-metrics-reporter#5]
Internal graylog metrics should be made available to graylog so that graylog can ingest and process these metrics.

The scenario I am aiming this at is to report on key metrics that graylog generates internally and have them available in a stream for alerting, pipelining and other types of lovely processing that I can do with graylog.

As a "belt and braces" approach to monitoring, I'd measure the value of "Uncommitted Journal Message Count" and action accordingly, however, I'd like to be able to also initiate an alert from within graylog.

While it is obviously "dangerous" to only rely on monitoring on a platform from within the platform that you are measuring, there is still value in doing so.  Multiple views of failure allow a robust view of overall environment health to be made.

**Comment by joschi** [comment]
@iainmcinnes This has been addressed with the new [`metrics-reporter-gelf`](https://github.com/Graylog2/graylog-plugin-metrics-reporter/tree/1.4.0/metrics-reporter-gelf) in version 1.4.0.

In the future, we might also add another metrics reporter which doesn't need to send the metrics over the network.
